# Generated by Django 5.1.6 on 2025-03-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_role_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.AddField(
            model_name='role',
            name='controller',
            field=models.CharField(default='Default Controller', max_length=100),
        ),
        migrations.AddField(
            model_name='role',
            name='duelist',
            field=models.CharField(default='Default Controller', max_length=100),
        ),
        migrations.AddField(
            model_name='role',
            name='initiator',
            field=models.CharField(default='Default Controller', max_length=100),
        ),
        migrations.AddField(
            model_name='role',
            name='sentinel',
            field=models.CharField(default='Default Controller', max_length=100),
        ),
    ]
