# Generated by Django 5.1.6 on 2025-04-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_author_delete_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Role',
        ),
    ]
