# Generated by Django 5.1.6 on 2025-04-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_remove_role_bio_remove_role_email_role_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.URLField()),
                ('location', models.CharField(max_length=100)),
                ('background', models.URLField()),
                ('map_type', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
